name: macOS

on:
  pull_request:
  push:

jobs:
  test:
    name: Test

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install cmake ninja python

    - name: Test
      run: ./bin/test.sh
