name: Windows

on:
  pull_request:
  push:

jobs:
  test:
    name: Test

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies (except YASM)
      shell: cmd
      run: choco install cmake python ninja nasm mingw llvm

    - name: Install YASM from local package
      shell: cmd
      run: choco install -source .github/workflows/ yasm

    - name: Test
      shell: cmd
      run: 'set "PATH=C:\Program Files\NASM;C:\Program Files\LLVM\bin;%PATH%" && bin\test.bat'
